import type { Metadata } from "next";
import "./globals.css";
import { TopNavbar } from "@/components/shared";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <div className="top-0 fixed w-full z-50">
          <TopNavbar />
        </div>
        <div className="pt-32 h-full">{children}</div>
      </body>
    </html>
  );
}
